[odiafactswiki]
title = "Wikipedia — did you know?"
url = "https://odishatv.in/"
entrySelector = ".item-inner .clearfix"
titleSelector = "h2.title>a>span"
imageSelector = ".featured .featured-type-featured-image > a"
